(define function (do (i 0 (+ i 1)) (> 4 i) (if (< i 8) (+ i 5) (cond [(< i 3) (display (* 2 i))][else (read)]))));kjhagsdfjhasfkj
(- 8 5)
(* 6 2)
(/ 3 4)
(remainder 1234 2)
(>= 7 8)
(<= 8 9)
(eq? i 8)
(neq? 9 xd)
(define string "string")
(define character 'c')
(cons 4 (cons 3 (cons 4 lst)))
(cons 4 (cons 3 (cons 4 '())))
(cdr (cons 4 (cons 3 5)))
(car (cons 4 (cons 3 5)))